// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistenz.Kontexte;

#nullable disable

namespace Persistenz.Migrations
{
    [DbContext(typeof(BasisDbKontext))]
    [Migration("20220910182919_Modelle_Erstellen")]
    partial class Modelle_Erstellen
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Einheiten.Marke", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Marken", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Porsche"
                        },
                        new
                        {
                            Id = 2,
                            Name = "BMW"
                        });
                });

            modelBuilder.Entity("Domain.Einheiten.Modell", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("BildUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("BildUrl");

                    b.Property<int>("MarkeId")
                        .HasColumnType("int")
                        .HasColumnName("MarkeId");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Name");

                    b.Property<decimal>("TagesPreis")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TagesPreis");

                    b.HasKey("Id");

                    b.HasIndex("MarkeId");

                    b.ToTable("Modelle", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BildUrl = "",
                            MarkeId = 1,
                            Name = "Panamera",
                            TagesPreis = 1000m
                        },
                        new
                        {
                            Id = 2,
                            BildUrl = "",
                            MarkeId = 2,
                            Name = "760 LI",
                            TagesPreis = 1100m
                        },
                        new
                        {
                            Id = 3,
                            BildUrl = "",
                            MarkeId = 1,
                            Name = "Cayenne",
                            TagesPreis = 1000m
                        });
                });

            modelBuilder.Entity("Domain.Einheiten.Modell", b =>
                {
                    b.HasOne("Domain.Einheiten.Marke", "Marke")
                        .WithMany("Modelle")
                        .HasForeignKey("MarkeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Marke");
                });

            modelBuilder.Entity("Domain.Einheiten.Marke", b =>
                {
                    b.Navigation("Modelle");
                });
#pragma warning restore 612, 618
        }
    }
}
